<div class="page-top" id="templatemo_services">
</div> <!-- /.page-header -->

<div class="middle-content">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="widget-item">
                    <h3 class="widget-title">Latest News</h3>
                    <div class="post-small">
                        <div class="post-date">
                            <span class="time">18</span>
                            <span>June</span>
                        </div> <!-- /.post-thumb -->
                        <div class="post-content">
                            <h4><a href="#">Lorem Ipsum</a></h4>
                            <span>Donec auctor iaculis</span>
                            <p>Nunc aliquam vestibulum veliesat, et aliquet lorem aliquet nec. Sed orsum rhoncus ipsum imperdiet accumsan laoreient.</p>
                        </div> <!-- /.post-content -->
                    </div> <!-- /.post-small -->
                    <div class="post-small">
                        <div class="post-date">
                            <span class="time">14</span>
                            <span>June</span>
                        </div> <!-- /.post-thumb -->
                        <div class="post-content">
                            <h4><a href="#">Lorem Ipsum</a></h4>
                            <span>Donec auctor iaculis</span>
                            <p>Nunc aliquam vestibulum veliesat, et aliquet lorem aliquet nec. Sed orsum rhoncus ipsum imperdiet accumsan laoreient.</p>
                        </div> <!-- /.post-content -->
                    </div> <!-- /.post-small -->
                    <div class="post-small">
                        <div class="post-date">
                            <span class="time">12</span>
                            <span>June</span>
                        </div> <!-- /.post-thumb -->
                        <div class="post-content">
                            <h4><a href="#">Lorem Ipsum</a></h4>
                            <span>Donec auctor iaculis</span>
                            <p>Nunc aliquam vestibulum veliesat, et aliquet lorem aliquet nec. Sed orsum rhoncus ipsum imperdiet accumsan laoreient.</p>
                        </div> <!-- /.post-content -->
                    </div> <!-- /.post-small -->
                </div> <!-- /.widget-item -->
            </div> <!-- /.col-md-4 -->
            <div class="col-md-4">
                <div class="widget-item">
                    <h3 class="widget-title">Consulting</h3>
                    <div class="sample-thumb">
                        <img src="images/event_1.jpg" alt="">
                    </div> <!-- /.sample-thumb -->
                    <h4 class="consult-title">Donec auctor iaculis libero ut ullamcorper</h4>
                    <p>Praesent ornare commodo tincidunt. Interdum et fames ac ante ipsum primis in faucibus. Aliquam justo lectus, fermentum vitae libero, tincidunt accumsan magns. <br><br>Vestibulum congue lorem odio, at sodales nisi luctus quis. Suspendisse suscipit ligula libero, id consectetur magna dictum sed.</p>
                </div> <!-- /.widget-item -->
            </div> <!-- /.col-md-4 -->
            <div class="col-md-4">
                <div class="widget-item">
                    <h3 class="widget-title">Our Services</h3>
                    <div class="service-item">
                        <div class="service-icon">
                            <i class="fa fa-bell-o"></i>
                        </div> <!-- /.service-icon -->
                        <div class="service-content">
                            <h4>Lorem Ipsum</h4>
                            <p>Change icons by <a rel="nofollow" href="http://fontawesome.info/font-awesome-icon-world-map/">Font Awesome</a> (version 4). Example: <strong>&lt;i class=&quot;fa fa-bell-o&quot;&gt;&lt;/i&gt;</strong></p>
                        </div> <!-- /.service-content -->
                    </div> <!-- /.service-item -->
                    <div class="service-item">
                        <div class="service-icon">
                            <i class="fa fa-cogs"></i>
                        </div> <!-- /.service-icon -->
                        <div class="service-content">
                            <h4>Lorem Ipsum</h4>
                            <p>Nunc aliquam vestibulum veliesat, et aliquet lorem aliquet nec. Sed orsum rhoncus.</p>
                        </div> <!-- /.service-content -->
                    </div> <!-- /.service-item -->
                    <div class="service-item">
                        <div class="service-icon">
                            <i class="fa fa-pencil"></i>
                        </div> <!-- /.service-icon -->
                        <div class="service-content">
                            <h4>Lorem Ipsum</h4>
                            <p>Nunc aliquam vestibulum veliesat, et aliquet lorem aliquet nec. Sed orsum rhoncus.</p>
                        </div> <!-- /.service-content -->
                    </div> <!-- /.service-item -->
                </div> <!-- /.widget-item -->
            </div> <!-- /.col-md-4 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</div> <!-- /.middle-content -->



<div class="go-act">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="first-map"></div>
            </div> <!-- /.col-md-4 -->
            <div class="col-md-8">
                <div class="act-btn">
                    <div class="inner">
                        <div class="price">
                            $4,800
                        </div> <!-- /.price -->
                        <div class="title">
                            <h2>Europa Tour</h2>
                            <span>Italy, Germany, France, Spain, England</span>
                        </div>
                    </div> <!-- /.inner -->
                    <a href="#" class="link">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div> <!-- /.act-btn -->
            </div> <!-- /.col-md-8 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</div> <!-- /.go-act -->



<div class="ticket-list">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="ticket-item">
                    <h4><a href="#">Airlines</a></h4>
                    <p>Travel is free responsive HTML5 template from <span class="blue">template</span><span class="green">mo</span>. You may download, edit and use this template for your travel related websites.<br><br> Aliquam justo lectus, fermentum vitae libero sollicitudin, tincidunt accumsan magna.Vestibulum congue lorem odio, at sodales nisi luctus quis.</p>
                    <a href="#" class="ticket-btn">Book a Ticket</a>
                </div> <!-- /.ticket-item -->
            </div> <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <div class="ticket-item">
                    <h4><a href="#">Best Cities</a></h4>
                    <p>Praesent ornare commodo tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam justo lectus, fermentum vitae libero sollicitudin, tincidunt accumsan magna. <br><br>Vestibulum congue lorem odio, at sodales nisi luctus quis. Suspendisse suscipit ligula libero, id consectetur magna dictum sed.</p>
                    <a href="#" class="ticket-btn">Book a Ticket</a>
                </div> <!-- /.ticket-item -->
            </div> <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <div class="ticket-item">
                    <h4><a href="#">Travel Guides</a></h4>
                    <p>Praesent ornare commodo tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam justo lectus, fermentum vitae libero sollicitudin, tincidunt accumsan magna. <br><br>Vestibulum congue lorem odio, at sodales nisi luctus quis. Suspendisse suscipit ligula libero, id consectetur magna dictum sed.</p>
                    <a href="#" class="ticket-btn">Book a Ticket</a>
                </div> <!-- /.ticket-item -->
            </div> <!-- /.col-md-3 -->
            <div class="col-md-3 col-sm-6">
                <div class="ticket-item">
                    <h4><a href="#">Special Events</a></h4>
                    <p>Praesent ornare commodo tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam justo lectus, fermentum vitae libero sollicitudin, tincidunt accumsan magna. <br><br>Vestibulum congue lorem odio, at sodales nisi luctus quis. Suspendisse suscipit ligula libero, id consectetur magna dictum sed.</p>
                    <a href="#" class="ticket-btn">Book a Ticket</a>
                </div> <!-- /.ticket-item -->
            </div> <!-- /.col-md-3 -->
        </div> <!-- /.row -->
    </div> <!-- /.container -->
</div> <!-- /.ticket-list -->